//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlMedicoWinForms.Utilidades.Idioma {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EnglishStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnglishStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ControlMedicoWinForms.Utilidades.Idioma.EnglishStrings", typeof(EnglishStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting added correctly.
        /// </summary>
        internal static string CitaAgregada {
            get {
                return ResourceManager.GetString("CitaAgregada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting edited correctly.
        /// </summary>
        internal static string CitaEditada {
            get {
                return ResourceManager.GetString("CitaEditada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new configuration has been saved, you must sign in again for it to take effect.
        /// </summary>
        internal static string ConfiguracionGuardada {
            get {
                return ResourceManager.GetString("ConfiguracionGuardada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to cancel?.
        /// </summary>
        internal static string ConfirmarCancelar {
            get {
                return ResourceManager.GetString("ConfirmarCancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove the selected meeting?.
        /// </summary>
        internal static string ConfirmarEliminarCita {
            get {
                return ResourceManager.GetString("ConfirmarEliminarCita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove the selected user?.
        /// </summary>
        internal static string ConfirmarEliminarUsuario {
            get {
                return ResourceManager.GetString("ConfirmarEliminarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to print the order?.
        /// </summary>
        internal static string ConfirmarImprimirOrden {
            get {
                return ResourceManager.GetString("ConfirmarImprimirOrden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit system?.
        /// </summary>
        internal static string ConfirmarSalir {
            get {
                return ResourceManager.GetString("ConfirmarSalir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnosis saved correctly, do you want to add a recipe?.
        /// </summary>
        internal static string DiagnosticoAgregado {
            get {
                return ResourceManager.GetString("DiagnosticoAgregado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnosis edited correctly, do you want to add a recipe?.
        /// </summary>
        internal static string DiagnosticoEditado {
            get {
                return ResourceManager.GetString("DiagnosticoEditado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specialty added correctly.
        /// </summary>
        internal static string EspecialidadAgregada {
            get {
                return ResourceManager.GetString("EspecialidadAgregada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specialty edited correctly.
        /// </summary>
        internal static string EspecialidadEditada {
            get {
                return ResourceManager.GetString("EspecialidadEditada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specimen saved correctly.
        /// </summary>
        internal static string EspecimenAgregado {
            get {
                return ResourceManager.GetString("EspecimenAgregado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specimen edited correctly.
        /// </summary>
        internal static string EspecimenEditado {
            get {
                return ResourceManager.GetString("EspecimenEditado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Civil Status.
        /// </summary>
        internal static string GridCampoEstadoCivil {
            get {
                return ResourceManager.GetString("GridCampoEstadoCivil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Phone.
        /// </summary>
        internal static string GridCampoMovil {
            get {
                return ResourceManager.GetString("GridCampoMovil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string GridCampoNombre {
            get {
                return ResourceManager.GetString("GridCampoNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        internal static string GridCampoTelefono {
            get {
                return ResourceManager.GetString("GridCampoTelefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medicine saved correctly.
        /// </summary>
        internal static string MedicamentoAgregado {
            get {
                return ResourceManager.GetString("MedicamentoAgregado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medicine edited correctly.
        /// </summary>
        internal static string MedicamentoEditado {
            get {
                return ResourceManager.GetString("MedicamentoEditado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medic saved correctly.
        /// </summary>
        internal static string MedicoAgregado {
            get {
                return ResourceManager.GetString("MedicoAgregado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string menuAgregar {
            get {
                return ResourceManager.GetString("menuAgregar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dates.
        /// </summary>
        internal static string menuCita {
            get {
                return ResourceManager.GetString("menuCita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clients.
        /// </summary>
        internal static string menuCliente {
            get {
                return ResourceManager.GetString("menuCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnostics.
        /// </summary>
        internal static string menuDiagnostico {
            get {
                return ResourceManager.GetString("menuDiagnostico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string menuEditar {
            get {
                return ResourceManager.GetString("menuEditar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string menuEliminar {
            get {
                return ResourceManager.GetString("menuEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        internal static string menuExpediente {
            get {
                return ResourceManager.GetString("menuExpediente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctors.
        /// </summary>
        internal static string menuMedico {
            get {
                return ResourceManager.GetString("menuMedico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        internal static string menuMiCuenta {
            get {
                return ResourceManager.GetString("menuMiCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        internal static string menuOrden {
            get {
                return ResourceManager.GetString("menuOrden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patients.
        /// </summary>
        internal static string menuPaciente {
            get {
                return ResourceManager.GetString("menuPaciente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipes.
        /// </summary>
        internal static string menuReceta {
            get {
                return ResourceManager.GetString("menuReceta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Off.
        /// </summary>
        internal static string menuSalir {
            get {
                return ResourceManager.GetString("menuSalir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MedTor.
        /// </summary>
        internal static string NombreAplicacion {
            get {
                return ResourceManager.GetString("NombreAplicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order saved correctly.
        /// </summary>
        internal static string OrdenAgregada {
            get {
                return ResourceManager.GetString("OrdenAgregada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order edited correctly.
        /// </summary>
        internal static string OrdenEditada {
            get {
                return ResourceManager.GetString("OrdenEditada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient saved correctly.
        /// </summary>
        internal static string PacienteAgregado {
            get {
                return ResourceManager.GetString("PacienteAgregado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient edited correctly.
        /// </summary>
        internal static string PacienteEditado {
            get {
                return ResourceManager.GetString("PacienteEditado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pathology saved correctly.
        /// </summary>
        internal static string PatologiaAgregada {
            get {
                return ResourceManager.GetString("PatologiaAgregada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pathology edited correctly.
        /// </summary>
        internal static string PatologiaEditada {
            get {
                return ResourceManager.GetString("PatologiaEditada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a meeting.
        /// </summary>
        internal static string SeleccionarCita {
            get {
                return ResourceManager.GetString("SeleccionarCita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a specialty.
        /// </summary>
        internal static string SeleccionarEspecialidad {
            get {
                return ResourceManager.GetString("SeleccionarEspecialidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a specimen.
        /// </summary>
        internal static string SeleccionarEspecimen {
            get {
                return ResourceManager.GetString("SeleccionarEspecimen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a medicine.
        /// </summary>
        internal static string SeleccionarMedicamento {
            get {
                return ResourceManager.GetString("SeleccionarMedicamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a pathology.
        /// </summary>
        internal static string SeleccionarPatologia {
            get {
                return ResourceManager.GetString("SeleccionarPatologia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string TextoBtnCancelar {
            get {
                return ResourceManager.GetString("TextoBtnCancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string TextoBtnEditar {
            get {
                return ResourceManager.GetString("TextoBtnEditar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string TextoBtnGuardar {
            get {
                return ResourceManager.GetString("TextoBtnGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string TextoBtnSalir {
            get {
                return ResourceManager.GetString("TextoBtnSalir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        internal static string TextoCampoClave {
            get {
                return ResourceManager.GetString("TextoCampoClave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        internal static string TextoCampoComentarios {
            get {
                return ResourceManager.GetString("TextoCampoComentarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string TextoCampoCorreo {
            get {
                return ResourceManager.GetString("TextoCampoCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string TextoCampoDescripcion {
            get {
                return ResourceManager.GetString("TextoCampoDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specimen.
        /// </summary>
        internal static string TextoCampoEspecimen {
            get {
                return ResourceManager.GetString("TextoCampoEspecimen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        internal static string TextoCampoGenero {
            get {
                return ResourceManager.GetString("TextoCampoGenero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medic.
        /// </summary>
        internal static string TextoCampoMedico {
            get {
                return ResourceManager.GetString("TextoCampoMedico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Family.
        /// </summary>
        internal static string TextoCampoNombreFamiliar {
            get {
                return ResourceManager.GetString("TextoCampoNombreFamiliar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient.
        /// </summary>
        internal static string TextoCampoPaciente {
            get {
                return ResourceManager.GetString("TextoCampoPaciente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Name.
        /// </summary>
        internal static string TextoCampoPrimerApellido {
            get {
                return ResourceManager.GetString("TextoCampoPrimerApellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string TextoCampoPrimerNombre {
            get {
                return ResourceManager.GetString("TextoCampoPrimerNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string TextoCampoTelefono {
            get {
                return ResourceManager.GetString("TextoCampoTelefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string TextoCampoTitulo {
            get {
                return ResourceManager.GetString("TextoCampoTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User saved correctly.
        /// </summary>
        internal static string UsuarioAgregado {
            get {
                return ResourceManager.GetString("UsuarioAgregado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User removed correctly.
        /// </summary>
        internal static string UsuarioEliminado {
            get {
                return ResourceManager.GetString("UsuarioEliminado", resourceCulture);
            }
        }
    }
}
