//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlMedicoApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArchivoPaciente
    {
        public int IdArchivoPaciente { get; set; }
        public int IdPaciente { get; set; }
        public int IdTipoArchivo { get; set; }
        public string Descripcion { get; set; }
        public System.Guid Codigo { get; set; }
        public byte[] Archivo { get; set; }
        public int Activo { get; set; }
        public string ExtensionArchivo { get; set; }
    
        public virtual TipoArchivo TipoArchivo { get; set; }
    }
}
