//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlMedicoApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfiguracionReporte
    {
        public int IdConfiguracionReporte { get; set; }
        public int IdTipoReporte { get; set; }
        public string Html { get; set; }
        public int IdMedico { get; set; }
        public int Activo { get; set; }
    
        public virtual Medico Medico { get; set; }
        public virtual TipoReporte TipoReporte { get; set; }
    }
}
