//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlMedicoApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ControlMedicoFileDBEntities : DbContext
    {
        public ControlMedicoFileDBEntities()
            : base("name=ControlMedicoFileDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ArchivoPaciente> ArchivoPaciente { get; set; }
        public virtual DbSet<TipoArchivo> TipoArchivo { get; set; }
        public virtual DbSet<ArchivoDiagnostico> ArchivoDiagnostico { get; set; }
        public virtual DbSet<ArchivoOrden> ArchivoOrden { get; set; }
        public virtual DbSet<ArchivoMedico> ArchivoMedico { get; set; }
    }
}
