//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlMedicoApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ControlMedicoDBEntities : DbContext
    {
        public ControlMedicoDBEntities()
            : base("name=ControlMedicoDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Especialidad> Especialidads { get; set; }
        public virtual DbSet<Cliente> Clientes { get; set; }
        public virtual DbSet<EstatusSuscripcion> EstatusSuscripcions { get; set; }
        public virtual DbSet<Suscripcion> Suscripcions { get; set; }
        public virtual DbSet<EstatusCita> EstatusCitas { get; set; }
        public virtual DbSet<Escolaridad> Escolaridads { get; set; }
        public virtual DbSet<EstatusTransaccion> EstatusTransaccions { get; set; }
        public virtual DbSet<OperacionContable> OperacionContables { get; set; }
        public virtual DbSet<TipoTransaccion> TipoTransaccions { get; set; }
        public virtual DbSet<Medicamento> Medicamentoes { get; set; }
        public virtual DbSet<TipoCita> TipoCitas { get; set; }
        public virtual DbSet<Institucion> Institucions { get; set; }
        public virtual DbSet<Medico> Medicos { get; set; }
        public virtual DbSet<Ocupacion> Ocupacions { get; set; }
        public virtual DbSet<RecetaMedicamento> RecetaMedicamentoes { get; set; }
        public virtual DbSet<EstatusOrden> EstatusOrdens { get; set; }
        public virtual DbSet<PacienteMedico> PacienteMedicoes { get; set; }
        public virtual DbSet<Transaccion> Transaccions { get; set; }
        public virtual DbSet<HistoricoOrden> HistoricoOrdens { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Orden> Ordens { get; set; }
        public virtual DbSet<ExistenciaMedicamento> ExistenciaMedicamentoes { get; set; }
        public virtual DbSet<InventarioMedicamento> InventarioMedicamentoes { get; set; }
        public virtual DbSet<Receta> Recetas { get; set; }
        public virtual DbSet<LugarNacimiento> LugarNacimientoes { get; set; }
        public virtual DbSet<Paciente> Pacientes { get; set; }
        public virtual DbSet<Diagnostico> Diagnosticoes { get; set; }
        public virtual DbSet<MedioNotificacion> MedioNotificacions { get; set; }
        public virtual DbSet<TipoNotificacion> TipoNotificacions { get; set; }
        public virtual DbSet<Configuracion> Configuracions { get; set; }
        public virtual DbSet<ConfiguracionMedico> ConfiguracionMedicoes { get; set; }
        public virtual DbSet<Notificacion> Notificacions { get; set; }
        public virtual DbSet<Especiman> Especimen { get; set; }
        public virtual DbSet<Patologia> Patologias { get; set; }
        public virtual DbSet<Cita> Citas { get; set; }
        public virtual DbSet<ConfiguracionReporte> ConfiguracionReportes { get; set; }
        public virtual DbSet<TipoReporte> TipoReportes { get; set; }
        public virtual DbSet<TipoReporteVariable> TipoReporteVariables { get; set; }
    }
}
