//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlMedicoApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExistenciaMedicamento
    {
        public int IdExistenciaMedicamento { get; set; }
        public int IdMedicamento { get; set; }
        public int Total { get; set; }
    
        public virtual Medicamento Medicamento { get; set; }
    }
}
