//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlMedicoApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoricoOrden
    {
        public int IdHistoricoOrden { get; set; }
        public int IdOrden { get; set; }
        public int IdEstatusOrden { get; set; }
        public string ClaveOrden { get; set; }
        public System.DateTime FechaEstatus { get; set; }
        public Nullable<int> IdUsuarioModificacion { get; set; }
    
        public virtual EstatusOrden EstatusOrden { get; set; }
        public virtual Orden Orden { get; set; }
    }
}
