//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlMedicoApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medico
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Medico()
        {
            this.Medicamentoes = new HashSet<Medicamento>();
            this.PacienteMedicoes = new HashSet<PacienteMedico>();
            this.Ordens = new HashSet<Orden>();
            this.Recetas = new HashSet<Receta>();
            this.Diagnosticoes = new HashSet<Diagnostico>();
            this.Citas = new HashSet<Cita>();
            this.ConfiguracionReportes = new HashSet<ConfiguracionReporte>();
        }
    
        public int IdMedico { get; set; }
        public string Nombre { get; set; }
        public string Telefono { get; set; }
        public Nullable<int> IdEspecialidad { get; set; }
        public int Activo { get; set; }
        public string Correo { get; set; }
        public int IdSuscripcion { get; set; }
        public Nullable<int> IdInstitucion { get; set; }
        public string CedulaProfesional { get; set; }
        public byte[] Foto { get; set; }
    
        public virtual Especialidad Especialidad { get; set; }
        public virtual Institucion Institucion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Medicamento> Medicamentoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PacienteMedico> PacienteMedicoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orden> Ordens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Receta> Recetas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Diagnostico> Diagnosticoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cita> Citas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConfiguracionReporte> ConfiguracionReportes { get; set; }
    }
}
