//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlMedicoApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notificacion
    {
        public int IdNotificacion { get; set; }
        public int IdMedico { get; set; }
        public Nullable<int> IdPaciente { get; set; }
        public Nullable<int> IdTipoNotificacion { get; set; }
        public Nullable<int> Recursivo { get; set; }
        public Nullable<int> IdMedioNotificacion { get; set; }
        public Nullable<System.DateTime> FechaNotificacion { get; set; }
        public Nullable<System.DateTime> HoraNotificacion { get; set; }
        public int Activo { get; set; }
        public Nullable<int> IdCita { get; set; }
    }
}
