//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlMedicoApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paciente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Paciente()
        {
            this.Ordens = new HashSet<Orden>();
            this.PacienteMedicoes = new HashSet<PacienteMedico>();
            this.Recetas = new HashSet<Receta>();
            this.Diagnosticoes = new HashSet<Diagnostico>();
            this.Citas = new HashSet<Cita>();
        }
    
        public int IdPaciente { get; set; }
        public string PrimerNombre { get; set; }
        public string Telefono { get; set; }
        public string EstadoCivil { get; set; }
        public string Identificacion { get; set; }
        public int Activo { get; set; }
        public int IdSuscripcion { get; set; }
        public string CorreoElectronico { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public string Direccion { get; set; }
        public Nullable<int> Escolaridad { get; set; }
        public Nullable<int> Patologia { get; set; }
        public Nullable<int> IdLugarNacimiento { get; set; }
        public string NombreFamiliar { get; set; }
        public string TelefonoFamiliar { get; set; }
        public string Observaciones { get; set; }
        public string Genero { get; set; }
        public Nullable<int> MedicamentoActual { get; set; }
        public string Religion { get; set; }
        public Nullable<int> IdOcupacion { get; set; }
        public Nullable<int> SeguroVida { get; set; }
        public Nullable<int> IdMedico { get; set; }
        public string SegundoNombre { get; set; }
        public string PrimerApellido { get; set; }
        public string SegundoApellido { get; set; }
        public string TelefonoMovil { get; set; }
    
        public virtual Escolaridad Escolaridad1 { get; set; }
        public virtual LugarNacimiento LugarNacimiento { get; set; }
        public virtual Ocupacion Ocupacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orden> Ordens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PacienteMedico> PacienteMedicoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Receta> Recetas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Diagnostico> Diagnosticoes { get; set; }
        public virtual Patologia Patologia1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cita> Citas { get; set; }
    }
}
