//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlMedicoApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecetaMedicamento
    {
        public int IdRecetaMedicamento { get; set; }
        public int IdReceta { get; set; }
        public Nullable<int> IdMedicamento { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public string Frecuencia { get; set; }
    
        public virtual Medicamento Medicamento { get; set; }
        public virtual Receta Receta { get; set; }
    }
}
