//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlMedicoApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Receta()
        {
            this.RecetaMedicamentoes = new HashSet<RecetaMedicamento>();
        }
    
        public int IdReceta { get; set; }
        public int IdPaciente { get; set; }
        public int IdMedico { get; set; }
        public Nullable<int> IdDiagnostico { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public int Activo { get; set; }
    
        public virtual Medico Medico { get; set; }
        public virtual Receta Receta1 { get; set; }
        public virtual Receta Receta2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecetaMedicamento> RecetaMedicamentoes { get; set; }
        public virtual Paciente Paciente { get; set; }
    }
}
