//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlMedicoApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Suscripcion
    {
        public int IdSuscriptor { get; set; }
        public int IdCliente { get; set; }
        public int MaxUsuarios { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaFin { get; set; }
        public int Estatus { get; set; }
        public int Activo { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual EstatusSuscripcion EstatusSuscripcion { get; set; }
    }
}
