//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlMedicoApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoNotificacion
    {
        public int IdTipoNotificacion { get; set; }
        public int IdMedico { get; set; }
        public string Descripcion { get; set; }
        public int Clave { get; set; }
        public string Template { get; set; }
        public int Activo { get; set; }
    }
}
