//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlMedicoApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoReporteVariable
    {
        public int IdTipoReporteVariable { get; set; }
        public int IdTipoReporte { get; set; }
        public string Descripcion { get; set; }
        public string Entidad { get; set; }
        public string Tipo { get; set; }
        public string Propiedad { get; set; }
        public string Html { get; set; }
        public int Activo { get; set; }
    }
}
