//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlMedicoApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoArchivo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TipoArchivo()
        {
            this.ArchivoMedico = new HashSet<ArchivoMedico>();
            this.ArchivoPaciente = new HashSet<ArchivoPaciente>();
            this.ArchivoDiagnostico = new HashSet<ArchivoDiagnostico>();
            this.ArchivoOrden = new HashSet<ArchivoOrden>();
        }
    
        public int IdTipoArchivo { get; set; }
        public string Descripcion { get; set; }
        public int Activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArchivoMedico> ArchivoMedico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArchivoPaciente> ArchivoPaciente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArchivoDiagnostico> ArchivoDiagnostico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArchivoOrden> ArchivoOrden { get; set; }
    }
}
