//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlMedicoApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaccion
    {
        public int IdTransaccion { get; set; }
        public int IdTipoTransaccion { get; set; }
        public int IdOperacionContable { get; set; }
        public System.DateTime Fecha { get; set; }
        public int IdGenerado { get; set; }
        public decimal Monto { get; set; }
        public string NumReferencia { get; set; }
        public string Observaciones { get; set; }
        public int Estatus { get; set; }
        public Nullable<decimal> Saldo { get; set; }
        public Nullable<decimal> MontoPagado { get; set; }
    
        public virtual EstatusTransaccion EstatusTransaccion { get; set; }
        public virtual OperacionContable OperacionContable { get; set; }
        public virtual TipoTransaccion TipoTransaccion { get; set; }
    }
}
