//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlMedicoWinForms.Utilidades {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ControlMedicoWinForms.Utilidades.ValidationMessages", typeof(ValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor ingrese una dirección de correo válida.
        /// </summary>
        internal static string CampoEmail {
            get {
                return ResourceManager.GetString("CampoEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo {0} es obligatorio.
        /// </summary>
        internal static string CampoVacio {
            get {
                return ResourceManager.GetString("CampoVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No puede eliminar una cita que se encuentra agendada, debe cancelarla primero.
        /// </summary>
        internal static string ErrorEliminarCitaAgendada {
            get {
                return ResourceManager.GetString("ErrorEliminarCitaAgendada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrió un error inesperado, por favor contacte con el area de soporte.
        /// </summary>
        internal static string ErrorInesperado {
            get {
                return ResourceManager.GetString("ErrorInesperado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar el dia y hora de la cita.
        /// </summary>
        internal static string FechaHoraCita {
            get {
                return ResourceManager.GetString("FechaHoraCita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario o la contraseña son incorrectos, por favor verifique e intente de nuevo.
        /// </summary>
        internal static string LoginIncorrecto {
            get {
                return ResourceManager.GetString("LoginIncorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor verifique su conexión a internet.
        /// </summary>
        internal static string SinConexion {
            get {
                return ResourceManager.GetString("SinConexion", resourceCulture);
            }
        }
    }
}
